HOMEWORK


🔹 Step 1: Import and Data

In [19]:
import random
import math

data = [random.randint(1, 50) for _ in range(5)]
print("Data:", data)


Data: [25, 49, 15, 43, 45]


🔹 Step 2: Mean

In [20]:
mean = sum(data) / len(data)
print("Mean:", mean)


Mean: 35.4


🔹 Step 3: Variance and Standard Deviation

In [21]:
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_dev = math.sqrt(variance)

print("Standard Deviation:", std_dev)


Standard Deviation: 13.108775686539152


🔹 Step 4: Z-score

In [22]:
z_scores = [(x - mean) / std_dev for x in data]
print("Z-Scores:", z_scores)


Z-Scores: [-0.7933616570065593, 1.0374729360855008, -1.556209404128251, 0.5797642878124858, 0.7323338372368242]


TRIAL

In [23]:
# --------------------------------------------
# Z-SCORE CALCULATION EXAMPLE
# --------------------------------------------

import math

# Step 1: Create a small dataset manually
data = [10, 20, 30, 40, 50]
print("Data:", data)

# Step 2: Calculate Mean
# Mean = Sum of values / Total number of values
mean = sum(data) / len(data)
print("Mean:", mean)

# Step 3: Calculate Variance
# Variance = Σ (X - Mean)^2 / N
variance = sum((x - mean) ** 2 for x in data) / len(data)
print("Variance:", variance)

# Step 4: Calculate Standard Deviation
# Standard Deviation = √Variance
std_dev = math.sqrt(variance)
print("Standard Deviation:", std_dev)

# Step 5: Calculate Z-Score
# Z = (X - Mean) / Standard Deviation
z_scores = [(x - mean) / std_dev for x in data]
print("Z-Scores:", z_scores)

# --------------------------------------------
# Interpretation:
# Z = 0  -> value equals mean
# Z > 0  -> above mean
# Z < 0  -> below mean
# --------------------------------------------


Data: [10, 20, 30, 40, 50]
Mean: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951
Z-Scores: [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]


In [24]:
import random
import math

# Generate 5 random numbers
data = [random.randint(1, 50) for _ in range(5)]
print("Data:", data)

# Mean
mean = sum(data) / len(data)

# Variance
variance = sum((x - mean) ** 2 for x in data) / len(data)

# Standard deviation
std_dev = math.sqrt(variance)

# Z-score
z_scores = [(x - mean) / std_dev for x in data]

print("Z-Scores:", z_scores)


Data: [50, 50, 33, 2, 2]
Z-Scores: [1.043971786571549, 1.043971786571549, 0.25868327454870244, -1.1733134238459, -1.1733134238459]


FEATURE_SCALING 

In [25]:
import numpy as np

In [26]:
np.random.seed(861)  # For reproducibility
x = np.random.randint(1, 100000, size=5)
print(x)

[17582 91167 44706 24495 60895]


standardization using scikit-lear

In [27]:
from sklearn.preprocessing import StandardScaler    
s=StandardScaler()
x_scaled=s.fit_transform(x.reshape(-1,1))
print(x_scaled)

[[-1.13803965]
 [ 1.63608986]
 [-0.11547406]
 [-0.87742189]
 [ 0.49484574]]


In [28]:
from sklearn.preprocessing import StandardScaler    
s=StandardScaler()
x_scaled=s.fit_transform([x])
print(x_scaled)

[[0. 0. 0. 0. 0.]]


Standardization from Scratch

In [29]:
# mean=np.mean(data)
# print(mean)

s,n=0,0
for i in x:
    s+=i
    n=n+1
mean = s/n
print(mean)


47769.0


In [ ]:
# sdeviation =np.std(x)
# print(sdeviation)

sq=0
for i in x:
    sq=sq+((i-mean)**2)

std=(sq/len(x))**(1/2)
print(std)

26525.437956799127


In [31]:
x_scaled=[]
for i in x:
    x_scaled.append((i-mean)/std)
print(x_scaled)


[np.float64(-1.1380396451573884), np.float64(1.636089857241208), np.float64(-0.11547405946656113), np.float64(-0.8774218935764753), np.float64(0.4948457409592169)]


Normalization using sckit-learn

In [39]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_scaled2 = mms.fit_transform(x.reshape(-1,1))
print(X_scaled2)

[[0.        ]
 [1.        ]
 [0.36860773]
 [0.09394578]
 [0.58861181]]


In [35]:
# min=np.min(x)
# max=np.max(x)   

min,max=x[0],x[0]

for i in x:
    if i>max:
        max=i
    elif i<min:
        min=i   
print("Min:", min)
print("Max:", max)  



Min: 17582
Max: 91167


In [36]:
X_scaled2=[]
for i in x:
    X_scaled2.append((i-min)/(max-min)) 

print(X_scaled2)

[np.float64(0.0), np.float64(1.0), np.float64(0.36860773255418905), np.float64(0.0939457769925936), np.float64(0.5886118094720392)]
